server:
  port: 5566
spring:
  redis:
    host: node.td-k8s.com
    port: 1379
    password: mWRK6joVy5No
    database: 5
    timeout: 2000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:sqlserver://10.100.12.101:1433;DatabaseName=www_JunTe_com
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: td_fqb
    password: tuandaiisverygood.0.2123
    hikari:
      connection-timeout: 2000


mybatis:
  mapper-locations: classpath:mapping/*.xml


